
version: 2.1

defaults: &defaults
  docker:
  - image: nervesproject/nerves_system_br:latest

install_ghr: &install_ghr
  run:
    name: Install ghr (Github Releases)
    command: |
      wget https://github.com/tcnksm/ghr/releases/download/v0.9.0/ghr_v0.9.0_linux_amd64.tar.gz
      tar xf ghr_v0.9.0_linux_amd64.tar.gz
      ln -sf ghr_v0.9.0_linux_amd64/ghr .

jobs:
  build_up_board:
    <<: *defaults
    steps:
      - checkout
      - run: echo "up_board" > .ci_config
      - run: "./create-build.sh configs/up_board_defconfig build"
      - run: "cd build && make"
      - store_artifacts:
          path: build/images
          destination: images
      - run:
          name: Copy deployment files
          command: mkdir -p deploy
      - run:
          name: Copy deployment fw
          command: cp build/images/*.fw deploy
      - save_cache:
          key: deploy/{{ checksum ".ci_config" }}-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
          paths:
            - deploy

  build_onlogic_cl210:
    <<: *defaults
    steps:
      - checkout
      - run: echo "onlogic_cl210" > .ci_config
      - run: "./create-build.sh configs/onlogic_cl210_defconfig build"
      - run: "cd build && make"
      - store_artifacts:
          path: build/images
          destination: images
      - run:
          name: Copy deployment files
          command: mkdir -p deploy
      - run:
          name: Copy deployment fw
          command: cp build/images/*.fw deploy
      - save_cache:
          key: deploy/{{ checksum ".ci_config" }}-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
          paths:
            - deploy

  deploy:
    <<: *defaults
    steps:
      - checkout
      - <<: *install_ghr
      - run:
          name: up_board
          command: echo "up_board" > .ci_config
      - restore_cache:
          key: deploy/{{ checksum ".ci_config" }}-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
      - run:
          name: onlogic_cl210
          command: echo "onlogic_cl210" > .ci_config
      - restore_cache:
          key: deploy/{{ checksum ".ci_config" }}-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
      - run:
          name: Create release notes
          command: grep -Pazo "(?s)(?<=## ${CIRCLE_TAG})[^#]+" CHANGELOG.md | sed '/./,$!d' > RELEASE_NOTES
      - run:
          name: Deploy artifacts to Github
          command: ./ghr -draft -t ${GITHUB_TOKEN}  -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -b "$(cat RELEASE_NOTES)" -replace $CIRCLE_TAG deploy

workflows:
  version: 2
  pipeline:
    jobs:
      - build_up_board:
          context: org-global
          filters:
            tags:
              only: /.*/
      - build_onlogic_cl210:
          context: org-global
          filters:
            tags:
              only: /.*/
      - deploy:
          context: org-global
          requires:
            - build_up_board
            - build_onlogic_cl210
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/

